### PR TITLE
Add support for Python 3.8

### PR DESCRIPTION
**Pull request by mushifali**
We need to use Flask-Mobility package on Python 3.8 but it's currently not supported. I ran the unit tests using Python 3.8 and it's working fine.

### CODE REVIEW

**Comment by rehandalal** [comment]
Thanks for verifying the tests and submitting this PR. 

I would probably also want to see CI updated to reflect this before making this change. There is a single file (https://github.com/rehandalal/flask-mobility/blob/master/.circleci/config.yml) that would need to be updated so that Python 3.8 becomes the default and we retain tests for each of Py3.5-3.8.

**Review by rehandalal — CHANGES_REQUESTED** [review]
CI needs to be updated before we commit this

**Comment by mushifali** [comment]
> Thanks for verifying the tests and submitting this PR.
> 
> I would probably also want to see CI updated to reflect this before making this change. There is a single file (https://github.com/rehandalal/flask-mobility/blob/master/.circleci/config.yml) that would need to be updated so that Python 3.8 becomes the default and we retain tests for each of Py3.5-3.8.

> CI needs to be updated before we commit this

@rehandalal Thank you for letting me know that I missed updating the CI. I have updated the CI, can you please review the change?

**Comment by rehandalal** [comment]
Oops I just realized that I had not configured Circle CI to run for forked pull requests so we did not get CI checks for this PR. 

Any chance you could no-op `--amend` your last commit and force push? 

```
git commit --amend
```

I believe that should trigger a CI build.

**Comment by rehandalal** [comment]
Also thanks for your work on this! Much appreciated!!

**Comment by mushifali** [comment]
> Oops I just realized that I had not configured Circle CI to run for forked pull requests so we did not get CI checks for this PR.
> 
> Any chance you could no-op `--amend` your last commit and force push?
> 
> ```
> git commit --amend
> ```
> 
> I believe that should trigger a CI build.

I have forced push the commit and the Circle CI build is executed successfully.

**Comment by rehandalal** [comment]
Perfect, thank you!!

**Comment by mushifali** [comment]
@rehandalal Thank you for merging the PR. But I can't see the updated version on PyPi. Do we need to update the `flask_mobility.__version__`?

**Comment by rehandalal** [comment]
This will not update on PyPi till there is a new release. I will issue a new release soon.

**Comment by mushifali** [comment]
Okay, thank you!

**Pull request merged**
